Algoritmo "consumo"

Var

   distancia, combustivel, consumoMedio : real

Inicio

      escreval("Digite a distância percorrida: ")
      leia(distancia)
      escreval("Digite o combustível gasto: ")
      leia(combustivel)
      
      consumoMedio <- distancia / combustivel
      
      escreval("O consumo médio foi de ", consumoMedio:1:3," litros por Km rodado.")

Fimalgoritmo